In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, f1_score, precision_score

In [2]:
df = pd.read_csv("evgeni_set.csv")
df['age'] = df['age']/110 #нормализация

In [3]:
#Меня не устраивает что  в train_test_split может в тестовую выборку попасть 0 инфарктов или все 100
#поэтому разделю вручную и соеденю после деления обратно
df_heartattack_x = df[df['minf']==1].iloc[:, 1:]
df_heartattack_y = df[df['minf']==1].iloc[:, 0]
df_no_heartattack_x = df[df['minf']==0].iloc[:, 1:]
df_no_heartattack_y = df[df['minf']==0].iloc[:, 0]

In [4]:
df_heartattack_x_train, df_heartattack_x_test, df_heartattack_y_train, df_heartattack_y_test = train_test_split(df_heartattack_x, df_heartattack_y, test_size=0.2)
df_no_heartattack_x_train, df_no_heartattack_x_test, df_no_heartattack_y_train, df_no_heartattack_y_test = train_test_split(df_no_heartattack_x, df_no_heartattack_y, test_size=0.2)

In [5]:
x_train = pd.concat((df_heartattack_x_train, df_no_heartattack_x_train), axis=0)
y_train = pd.concat((df_heartattack_y_train, df_no_heartattack_y_train), axis=0)
x_test = pd.concat((df_heartattack_x_test, df_no_heartattack_x_test), axis=0)
y_test = pd.concat((df_heartattack_y_test, df_no_heartattack_y_test), axis=0)

#проверка соответствия id после склейки
if all(y_test.index==x_test.index) and all(y_train.index==x_train.index):
    print('Данные склеены правильно')

Данные склеены правильно


KNN

In [17]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=4, algorithm='ball_tree')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
matrix = confusion_matrix(y_test, y_pred)
print(matrix)
print("recall: "+str(recall_score(y_test, y_pred)))
print("precision: "+str(precision_score(y_test, y_pred)))
print("accuracy_score: "+str(accuracy_score(y_test, y_pred)))
print("Доля обектов отнесеных к классу 1 от тестовой выборки: "+str(round((sum(matrix[:, 1])/x_test.shape[0])*100))+'%')

[[761  28]
 [  0  21]]
recall: 1.0
precision: 0.42857142857142855
accuracy_score: 0.9654320987654321
Доля обектов отнесеных к классу 1 от тестовой выборки: 6%


e:\Anaconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [ ]:
y_pred = model.predict(x_train)
matrix = confusion_matrix(y_train, y_pred)
print(matrix)
print("recall: "+str(recall_score(y_train, y_pred)))
print("precision: "+str(precision_score(y_train, y_pred)))
print("accuracy_score: "+str(accuracy_score(y_train, y_pred)))
print("Доля обектов отнесеных к классу 1 от тестовой выборки: "+str(round((sum(matrix[:, 1])/x_test.shape[0])*100))+'%')


In [7]:
model.predict_proba(x_test)[(model.predict_proba(x_test)!=0)&(model.predict_proba(x_test)!=1)]

array([], dtype=float64)

In [8]:
import pickle
pickle.dump(model, open('knn_model.sav', 'wb'))

In [21]:
model.predict(x_test.iloc[0:2])

e:\Anaconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 1], dtype=int64)

[age                     0.645455
 man                     1.000000
 female                  0.000000
 SmokingAlcoholism       0.000000
 Fatness                 1.000000
 Diabetes                0.000000
 Hyperlipidemia          0.000000
 PhysicalInactivity      1.000000
 ArterialHypertension    1.000000
 Name: 3877, dtype: float64]

In [30]:
model.predict_proba([[0.645455, 1, 0, 0, 1, 0, 0, 1, 1]])

e:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [37]:
with open('knn_model.sav', 'rb') as fp:
   clf = pickle.load(fp)

In [38]:
clf.predict_proba([[0.645455, 1, 0, 0, 1, 0, 0, 1, 1]])

e:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[0., 1.]])